name: Cache Action
author: Alfi Maulana
description: Save caches
branding:
  icon: archive
  color: black
inputs:
  key:
    description: The key of the cache
    required: true
  version:
    description: The version of the cache
    required: true
  file:
    description: The file to cache
    required: true
runs:
  using: node20
  main: dist/index.mjs
