name: Cache Action
author: Alfi Maulana
description: Save and restore files as a cache
branding:
  icon: archive
  color: black
inputs:
  key:
    description: The cache key
    required: true
  version:
    description: The cache version
    required: true
  files:
    description: The files to be cached
    required: true
outputs:
  restored:
    description: A boolean value indicating whether the cache was successfully restored
runs:
  using: node24
  main: dist/action/main.bundle.mjs
  post: dist/action/post.bundle.mjs
  post-if: success()
