name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5.0.0

      - name: Setup pnpm
        uses: threeal/setup-pnpm-action@v1.0.0

      - name: Install Dependencies
        run: pnpm install

      - name: Check Types
        run: pnpm tsc

      - name: Test Project
        run: pnpm test

      - name: Check Formatting
        run: pnpm prettier --check .

      - name: Check Lint
        run: pnpm eslint

      - name: Package Library
        run: pnpm pack

      - name: Build Action
        run: pnpm rollup -c && git diff --exit-code dist/action

      - name: Build Documentation
        run: pnpm typedoc
