name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-package:
    name: Test Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: latest

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: stable

      - name: Test Package
        run: yarn test

  test-action-save-file:
    name: Test Action to Save File
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4.1.7
        with:
          path: cache-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Prepare File
        shell: bash
        run: echo "some value" >> file.txt

      - name: Save Cache
        id: save-cache
        uses: ./cache-action
        with:
          key: some-key-${{ matrix.os }}
          version: ${{ github.run_id }}
          file: file.txt

      - name: Check Output
        shell: bash
        run: test "${{ steps.save-cache.outputs.restored }}" == "false"

  test-action-restore-file:
    name: Test Action to Restore File
    needs: test-action-save-file
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4.1.7
        with:
          path: cache-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Restore Cache
        id: restore-cache
        uses: ./cache-action
        with:
          key: some-key-${{ matrix.os }}
          version: ${{ github.run_id }}
          file: file.txt

      - name: Check Output
        shell: bash
        run: test "${{ steps.restore-cache.outputs.restored }}" == "true"

      - name: Check File
        shell: bash
        run: test "$(cat file.txt)" == "some value"
