name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-package:
    name: Test Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: latest

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: stable

      - name: Test Package
        run: yarn test

  test-action:
    name: Test Action
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4.1.7
        with:
          path: cache-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Reserve Cache
        uses: ./cache-action
        with:
          key: some-key-${{ matrix.os }}
          version: ${{ github.run_id }}
          size: 1024
